  - shell: crossdev -S -t armv7a-hardfloat-linux-gnueabi
    args:
      creates: /usr/armv7a-hardfloat-linux-gnueabi
    tags:
    - crossdev

  - lineinfile:
      dest: /etc/portage/package.accept_keywords
      line: sys-boot/vboot-utils

  - portage:
      package: sys-boot/vboot-utils
