  - shell: crossdev -S -t armv7a-hardfloat-linux-gnueabi
    args:
      creates: /usr/armv7a-hardfloat-linux-gnueabi
    tags:
    - crossdev

  - lineinfile:
      dest: /etc/portage/package.accept_keywords/sys-boot
      line: sys-boot/vboot-utils
      create: yes

  - portage:
      package: sys-boot/vboot-utils
