  - shell: crossdev -s4 -S --target avr
    args:
      creates: /usr/avr
    environment:
      USE: -openmp -hardened -sanitize -vtv

  - file:
      path: /usr/avr/lib/ldscripts
      src: /usr/x86_64-pc-linux-gnu/avr/lib/ldscripts
      state: link

  - lineinfile:
      dest: /etc/portage/package.accept_keywords/dev-embedded
      line: dev-embedded/dfu-programmer
      create: yes

  - portage:
      package: dfu-programmer
