---
  - file:
      state: directory
      path: /etc/portage/repos.conf
    tags:
    - crossdev

  - file:
      state: directory
      path: "{{ item }}"
      owner: portage
      group: portage
    tags:
    - crossdev
    with_items:
      - /usr/local/portage-crossdev
      - /usr/local/portage-crossdev/profiles
      - /usr/local/portage-crossdev/metadata

  - template:
      dest: "/usr/local/portage-crossdev/{{ item.path }}"
      src: "roles/crossdev/templates/{{ item.template }}.j2"
      owner: portage
      group: portage
    with_items:
      - { path: profiles/repo_name, template: repo_name }
      - { path: metadata/layout.conf, template: layout.conf }
    tags:
    - crossdev

  - template: src=roles/crossdev/templates/crossdev.conf.j2 dest=/etc/portage/repos.conf/crossdev.conf
    tags:
    - crossdev

  - portage:
      package: "{{ item }}"
    with_items:
      - crossdev
      - u-boot-tools
      - dtc
    tags:
    - crossdev

