-       name: download repo
        get_url:
          url: https://storage.googleapis.com/git-repo-downloads/repo
          checksum: sha1:ac9d646f6d699f6822a6bc787d3e7338ae7ab6ed
          dest: /usr/local/bin/repo
          mode: 0755
        tags:
        - repo
